<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Version>5.0.0</Version>
    <Authors>Litenova Solutions</Authors>
    <Company>Litenova Solutions</Company>
    <Copyright>Copyright (c) Litenova Solutions 2026</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Litenova-Solutions/Fuse.git</RepositoryUrl>
  </PropertyGroup>
</Project>
