using DotMake.CommandLine;
using Fuse.Cli.Services;
using Fuse.Collection.Models;
using Fuse.Collection.Templates;
using Fuse.Emission.Models;
using Fuse.Fusion;
using Fuse.Reduction.Options;

namespace Fuse.Cli.Commands;

/// <summary>
///     Abstract base class for all Fuse CLI commands.
/// </summary>
public abstract class CommandBase
{
    /// <summary>
    ///     The fusion orchestrator for executing fusion operations.
    /// </summary>
    protected readonly FusionOrchestrator _orchestrator;

    /// <summary>
    ///     The template registry used to resolve extension defaults.
    /// </summary>
    protected readonly ProjectTemplateRegistry _templateRegistry;

    /// <summary>
    ///     The console UI for displaying status and output.
    /// </summary>
    protected readonly IConsoleUI _consoleUI;

    /// <summary>
    ///     Initializes a new instance of the <see cref="CommandBase" /> class.
    /// </summary>
    /// <param name="orchestrator">The fusion orchestrator instance.</param>
    /// <param name="templateRegistry">The project template registry.</param>
    /// <param name="consoleUI">The console UI instance.</param>
    protected CommandBase(
        FusionOrchestrator orchestrator,
        ProjectTemplateRegistry templateRegistry,
        IConsoleUI consoleUI)
    {
        _orchestrator = orchestrator;
        _templateRegistry = templateRegistry;
        _consoleUI = consoleUI;
    }

    /// <summary>
    ///     Executes a fusion request and displays results to the console.
    /// </summary>
    /// <param name="request">The fusion request to execute.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    protected async Task ExecuteFusionAsync(FusionRequest request, CancellationToken cancellationToken)
    {
        try
        {
            var result = await _orchestrator.FuseAsync(request, cancellationToken);

            if (result.ProcessedFileCount == 0)
            {
                _consoleUI.WriteError("No files found matching the criteria. Aborting.");
                return;
            }

            DisplayResults(result, request.Emission);
        }
        catch (FusionValidationException ex)
        {
            foreach (var error in ex.Errors)
            {
                _consoleUI.WriteError(error);
            }
        }
        catch (FusionException ex)
        {
            _consoleUI.WriteError($"Error: {ex.Message}");
        }
        catch (Exception ex)
        {
            _consoleUI.WriteError($"Error: {ex.Message}");
            if (ex.InnerException is not null)
            {
                _consoleUI.WriteError($"  {ex.InnerException.Message}");
            }
        }
    }

    /// <summary>
    ///     Creates a new fusion request builder preconfigured with common CLI options.
    /// </summary>
    /// <param name="template">The optional project template.</param>
    /// <returns>A configured fusion request builder.</returns>
    protected FusionRequestBuilder CreateRequestBuilder(ProjectTemplate? template = null)
    {
        var builder = new FusionRequestBuilder(_templateRegistry)
            .WithSourceDirectory(Directory)
            .WithMaxFileSizeKb(MaxFileSize)
            .WithCollectionBehavior(
                Recursive,
                IgnoreBinary,
                ExcludeEmptyFiles,
                ExcludeAutoGenerated,
                ExcludeTestProjects,
                excludeUnitTestProjects: false,
                RespectGitIgnore)
            .WithEmissionOptions(new EmissionOptions
            {
                OutputDirectory = Output,
                OutputFileName = OutputFileName,
                Overwrite = Overwrite,
                IncludeMetadata = IncludeMetadata,
                MaxTokens = MaxTokens,
                SplitTokens = SplitTokens,
                ShowTokenCount = ShowTokenCount,
                TrackTopTokenFiles = TrackTopTokenFiles
            })
            .WithReductionOptions(new ReductionOptions());

        if (template.HasValue)
        {
            builder.WithTemplate(template.Value);
        }

        if (OnlyExtensions?.Length > 0)
        {
            builder.WithOnlyExtensions(OnlyExtensions);
        }

        if (IncludeExtensions?.Length > 0)
        {
            builder.WithIncludeExtensions(IncludeExtensions);
        }

        if (ExcludeExtensions?.Length > 0)
        {
            builder.WithExcludeExtensions(ExcludeExtensions);
        }

        if (ExcludeDirectories?.Length > 0)
        {
            builder.WithExcludeDirectories(ExcludeDirectories);
        }

        if (ExcludeFiles?.Length > 0)
        {
            builder.WithExcludeFiles(ExcludeFiles);
        }

        if (ExcludePatterns?.Length > 0)
        {
            builder.WithExcludePatterns(ExcludePatterns);
        }

        return builder;
    }

    private void DisplayResults(FusionResult result, EmissionOptions emissionOptions)
    {
        _consoleUI.WriteSuccess("Fusion complete!");

        foreach (var path in result.GeneratedPaths)
        {
            var fileInfo = new FileInfo(path);
            var friendlyPath = ConsoleUI.GetFriendlyPath(path);
            _consoleUI.WriteResult($"Output: {friendlyPath}");
        }

        if (emissionOptions.ShowTokenCount)
        {
            var totalSizeKB = result.GeneratedPaths.Sum(p => new FileInfo(p).Length) / 1024.0;
            var tokensFormatted = result.TotalTokens >= 1000
                ? $"{result.TotalTokens / 1000.0:F0}k"
                : $"{result.TotalTokens}";

            _consoleUI.WriteResult(
                $"Stats:  {totalSizeKB:F0} KB | {tokensFormatted} tokens | {result.ProcessedFileCount}/{result.TotalFileCount} files | {result.Duration.TotalSeconds:F1}s");

            if (emissionOptions.TrackTopTokenFiles && result.TopTokenFiles.Count > 0)
            {
                _consoleUI.WriteResult("\nTop Token Consumers:");
                for (var i = 0; i < result.TopTokenFiles.Count; i++)
                {
                    var file = result.TopTokenFiles[i];
                    var count = file.Count >= 1000
                        ? $"{file.Count / 1000.0:F1}k"
                        : file.Count.ToString();
                    _consoleUI.WriteResult($"{i + 1}. {file.Path} ({count})");
                }
            }
        }
    }

    #region Test Project Options

    [CliOption(Description = "Exclude common test project directories.")]
    public bool ExcludeTestProjects { get; set; } = false;

    #endregion

    #region Extension Override Options

    [CliOption(Required = false, Description = "Additional file extensions to include alongside template defaults (e.g., .txt,.log).")]
    public string[]? IncludeExtensions { get; set; }

    [CliOption(Required = false, Description = "File extensions to remove from template defaults (e.g., .xml,.md).")]
    public string[]? ExcludeExtensions { get; set; }

    [CliOption(Required = false, Description = "Fuse ONLY the specified comma-separated file extensions, ignoring all template defaults.")]
    public string[]? OnlyExtensions { get; set; }

    #endregion

    #region Directory Options

    [CliOption(Description = "Path to the directory to process.")]
    public string Directory { get; set; } = System.IO.Directory.GetCurrentDirectory();

    [CliOption(Description = "Path to the output directory.")]
    public string Output { get; set; } = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "Fuse");

    [CliOption(Required = false, Description = "Directory names to exclude from scanning (e.g., Migrations, wwwroot).")]
    public string[]? ExcludeDirectories { get; set; }

    #endregion

    #region Output Options

    [CliOption(Name = "name", Required = false, Description = "Name of the output file (without extension).")]
    public string? OutputFileName { get; set; }

    [CliOption(Description = "Overwrite the output file if it exists.")]
    public bool Overwrite { get; set; } = true;

    #endregion

    #region Search Options

    [CliOption(Description = "Search recursively through subdirectories.")]
    public bool Recursive { get; set; } = true;

    [CliOption(Description = "Maximum file size in KB to process (0 for unlimited).")]
    public int MaxFileSize { get; set; } = 0;

    [CliOption(Description = "Ignore binary files.")]
    public bool IgnoreBinary { get; set; } = true;

    #endregion

    #region Content Options

    [CliOption(Description = "Include file metadata (size, dates) in the output.")]
    public bool IncludeMetadata { get; set; } = false;

    [CliOption(Description = "Respect rules from .gitignore files found in the directory tree.")]
    public bool RespectGitIgnore { get; set; } = true;

    #endregion

    #region Token Options

    [CliOption(Description = "Stops processing completely when token count is reached.")]
    public int? MaxTokens { get; set; }

    [CliOption(Description = "Split output into multiple files when this token count is exceeded.")]
    public int? SplitTokens { get; set; } = 800000;

    [CliOption(Description = "Displays the final estimated token count upon completion.")]
    public bool ShowTokenCount { get; set; } = true;

    [CliOption(Description = "Tracks and displays the top 5 files consuming the most tokens.")]
    public bool TrackTopTokenFiles { get; set; } = false;

    #endregion

    #region Exclusion Options

    [CliOption(Required = false, Description = "Exclude specific file names (e.g., appsettings.Development.json).")]
    public string[]? ExcludeFiles { get; set; }

    [CliOption(Required = false, Description = "Exclude files matching glob patterns (e.g., **/Migrations/**, **/*.min.js).")]
    public string[]? ExcludePatterns { get; set; }

    [CliOption(Description = "Skip empty (zero-byte) files.")]
    public bool ExcludeEmptyFiles { get; set; } = true;

    [CliOption(Description = "Skip files containing an auto-generated code marker in the first few lines.")]
    public bool ExcludeAutoGenerated { get; set; } = true;

    #endregion
}
