using DotMake.CommandLine;
using Fuse.Cli.Commands;
using Fuse.Collection.Models;
using Fuse.Fusion;
using Fuse.Reduction.Options;

namespace Fuse.Cli.Commands;

[CliCommand(Name = "dotnet", Description = "Fuse a .NET project, including C#, F#, and web files.", Parent = typeof(FuseCliCommand))]
public sealed class DotNetCommand : CommandBase
{
    public DotNetCommand() : base(null!, null!, null!)
    {
    }

    public DotNetCommand(
        FusionOrchestrator orchestrator,
        Fuse.Collection.Templates.ProjectTemplateRegistry templateRegistry,
        Fuse.Cli.Services.IConsoleUI consoleUI) : base(orchestrator, templateRegistry, consoleUI)
    {
    }

    public async Task RunAsync(CliContext context)
    {
        var request = CreateRequestBuilder(ProjectTemplate.DotNet)
            .WithCollectionBehavior(
                Recursive,
                IgnoreBinary,
                ExcludeEmptyFiles,
                ExcludeAutoGenerated,
                ExcludeTestProjects,
                ExcludeUnitTestProjects,
                RespectGitIgnore)
            .WithReductionOptions(new ReductionOptions(
                trimContent: true,
                useCondensing: true,
                removeCSharpComments: All || RemoveCSharpComments,
                removeCSharpUsings: All || RemoveCSharpUsings,
                removeCSharpNamespaces: All || RemoveCSharpNamespaces,
                removeCSharpRegions: All || RemoveCSharpRegions,
                aggressiveCSharpReduction: All || Aggressive,
                minifyXmlFiles: MinifyXmlFiles,
                minifyHtmlAndRazor: MinifyHtmlAndRazor))
            .Build();

        await ExecuteFusionAsync(request, context.CancellationToken);
    }

    [CliOption(Description = "Remove namespace declarations from C# files.")]
    public bool RemoveCSharpNamespaces { get; set; } = false;

    [CliOption(Description = "Remove comments from C# files.")]
    public bool RemoveCSharpComments { get; set; } = false;

    [CliOption(Description = "Remove #region directives from C# files.")]
    public bool RemoveCSharpRegions { get; set; } = false;

    [CliOption(Description = "Remove all using statements from C# files.")]
    public bool RemoveCSharpUsings { get; set; } = false;

    [CliOption(Description = "Apply aggressive reduction (remove attributes, redundant keywords, compress properties).")]
    public bool Aggressive { get; set; } = false;

    [CliOption(Description = "Minify XML files (.csproj, .xml, etc.).")]
    public bool MinifyXmlFiles { get; set; } = true;

    [CliOption(Description = "Minify HTML and Razor files.")]
    public bool MinifyHtmlAndRazor { get; set; } = true;

    [CliOption(Description = "Exclude only unit test project directories (keeps integration tests and benchmarks).")]
    public bool ExcludeUnitTestProjects { get; set; } = false;

    [CliOption(Description = "Apply all optimizations (remove namespaces, comments, regions, usings, aggressive reduction).")]
    public bool All { get; set; } = false;
}
