using Fuse.Collection.Filters;
using Fuse.Collection.Options;

namespace Fuse.Collection.Tests.Filters;

public sealed class AutoGeneratedFileFilterTests
{
    private readonly AutoGeneratedFileFilter _filter = new();

    [Fact]
    public void Include_ExcludeAutoGeneratedDisabled_ReturnsTrue()
    {
        var options = new CollectionOptions(@"C:\src", excludeAutoGenerated: false);
        var candidate = TestHelpers.CreateCandidate("Generated.cs", "// <auto-generated />");

        Assert.True(_filter.Include(candidate, options));
    }

    [Fact]
    public void Include_ManualFile_ReturnsTrue()
    {
        var options = TestHelpers.DefaultOptions();
        var candidate = TestHelpers.CreateCandidate("Program.cs", "namespace App;");

        Assert.True(_filter.Include(candidate, options));
    }

    [Fact]
    public void Include_AutoGeneratedMarker_ReturnsFalse()
    {
        var options = TestHelpers.DefaultOptions();
        var candidate = TestHelpers.CreateCandidate("Generated.cs", "// <auto-generated />");

        Assert.False(_filter.Include(candidate, options));
    }
}
