using Fuse.Collection.Models;
using Fuse.Collection.Options;

namespace Fuse.Collection.Filters;

/// <summary>
///     Excludes files that contain auto-generated markers in their first few lines.
/// </summary>
public sealed class AutoGeneratedFileFilter : IFileFilter
{
    /// <inheritdoc />
    public bool Include(FileCandidate candidate, CollectionOptions options)
    {
        if (!options.ExcludeAutoGenerated)
            return true;

        return !IsAutoGenerated(candidate.FullPath);
    }

    private static bool IsAutoGenerated(string filePath)
    {
        try
        {
            using var reader = new StreamReader(filePath, detectEncodingFromByteOrderMarks: true);
            for (var i = 0; i < 5; i++)
            {
                var line = reader.ReadLine();
                if (line == null)
                    break;

                if (line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) ||
                    line.Contains("<autogenerated", StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            return false;
        }
        catch
        {
            // Unreadable files are treated as not auto-generated so other filters can decide inclusion.
            return false;
        }
    }
}
