<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Fuse.Evals</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Fuse/Fuse.csproj" />
  </ItemGroup>

</Project>
