using System.Text;
using Fuse.Collection;
using Fuse.Collection.Options;
using Fuse.Indexing;

namespace Fuse.Semantics;

/// <summary>
///     Discovers source files in a workspace and produces <see cref="IndexedFileRecord" /> values with
///     content hashes and test/generated flags, ready to upsert into the index.
/// </summary>
/// <remarks>
///     Reuses <see cref="FileCollectionPipeline" /> for discovery (gitignore, extension, and exclusion
///     rules), then hashes each file once and classifies it from its path and a short content prefix.
///     Test and generated files are included and flagged, not excluded: retrieval decides how to treat
///     them.
/// </remarks>
public sealed class WorkspaceFileScanner
{
    private const int ContentPrefixBytes = 2048;

    /// <summary>
    ///     The default per-file size cap (bytes) above which a file is skipped rather than read into the index
    ///     (R35). A generated giant or a mislabeled binary would otherwise cost memory and time for no signal.
    ///     Override with the <c>FUSE_MAX_FILE_BYTES</c> environment variable.
    /// </summary>
    public const long DefaultMaxFileBytes = 5L * 1024 * 1024;

    /// <summary>The environment variable overriding <see cref="DefaultMaxFileBytes" />.</summary>
    public const string MaxFileBytesEnvVar = "FUSE_MAX_FILE_BYTES";

    private static readonly string[] DefaultExtensions = [".cs", ".csproj", ".props", ".targets", ".json"];

    private readonly FileCollectionPipeline _pipeline;
    private readonly FileHashService _hashService;
    // For a git work tree, enumerate the files git itself reports (tracked plus untracked-not-ignored), which
    // excludes other worktrees, embedded repositories, and ignored trees by construction. Best-effort: a non-git
    // directory falls back to the directory walk. Field-initialized like the indexer's co-change collector.
    private readonly GitFileEnumerator _gitFiles = new();

    /// <summary>
    ///     Initializes a new instance of the <see cref="WorkspaceFileScanner" /> class.
    /// </summary>
    /// <param name="pipeline">The collection pipeline used to discover files.</param>
    /// <param name="hashService">The service used to compute content hashes.</param>
    public WorkspaceFileScanner(FileCollectionPipeline pipeline, FileHashService hashService)
    {
        _pipeline = pipeline;
        _hashService = hashService;
    }

    /// <summary>
    ///     Discovers files under a root directory and builds their index records.
    /// </summary>
    /// <param name="request">The scan request.</param>
    /// <param name="cancellationToken">A token to cancel the scan.</param>
    /// <returns>The discovered files as index records, sorted by the pipeline's deterministic path order.</returns>
    public async Task<IReadOnlyList<IndexedFileRecord>> ScanAsync(FileScanRequest request, CancellationToken cancellationToken) =>
        (await ScanWithSkipsAsync(request, cancellationToken)).Files;

    /// <summary>
    ///     Discovers files under a root directory and builds their index records, also reporting the files skipped
    ///     (too large, unreadable, permission-denied) so one hostile file never aborts the index (R35).
    /// </summary>
    /// <param name="request">The scan request.</param>
    /// <param name="cancellationToken">A token to cancel the scan.</param>
    /// <returns>The index records and the skipped files with reasons.</returns>
    public async Task<FileScanResult> ScanWithSkipsAsync(FileScanRequest request, CancellationToken cancellationToken)
    {
        // Prefer git's own view of the working tree; null (not a git repo) falls back to the directory walk.
        var candidateFiles = await _gitFiles.TryListAsync(request.RootDirectory, cancellationToken);

        var options = new CollectionOptions(
            sourceDirectory: request.RootDirectory,
            extensions: (request.Extensions ?? DefaultExtensions).ToArray(),
            excludeDirectories: WorkspaceExclusions.LoadDirectoryNames(request.RootDirectory).ToArray(),
            recursive: true,
            ignoreBinaryFiles: true,
            excludeEmptyFiles: true,
            // Generated and test files are indexed (and flagged), not dropped, so retrieval can reason about them.
            excludeAutoGenerated: false,
            excludeTestProjects: false,
            excludeUnitTestProjects: false,
            respectGitIgnore: true,
            candidateFiles: candidateFiles);

        var collection = await _pipeline.CollectAsync(options, cancellationToken);
        var records = new List<IndexedFileRecord>(collection.Files.Count);
        var skipped = new List<SkippedFile>();
        var maxFileBytes = ResolveMaxFileBytes();

        foreach (var file in collection.Files)
        {
            cancellationToken.ThrowIfCancellationRequested();

            // R35: one hostile file (oversized, unreadable, permission-denied, or a mid-scan IO error) must never
            // abort the whole index. Skip it with a recorded reason and keep indexing the good files.
            if (maxFileBytes > 0 && file.FileInfo.Length > maxFileBytes)
            {
                skipped.Add(new SkippedFile(file.NormalizedRelativePath, $"too large ({file.FileInfo.Length} bytes > {maxFileBytes} cap)"));
                continue;
            }

            try
            {
                var bytes = await File.ReadAllBytesAsync(file.FullPath, cancellationToken);
                var hash = _hashService.ComputeHash(bytes);
                var prefix = DecodePrefix(bytes);

                records.Add(new IndexedFileRecord(
                    Path: file.RelativePath,
                    NormalizedPath: file.NormalizedRelativePath,
                    Extension: file.Extension,
                    SizeBytes: file.FileInfo.Length,
                    MtimeUtcTicks: file.FileInfo.LastWriteTimeUtc.Ticks,
                    ContentHash: hash,
                    IsGenerated: FileClassifier.IsGenerated(file.NormalizedRelativePath, prefix),
                    IsTest: FileClassifier.IsTestFile(file.NormalizedRelativePath, prefix)));
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Security.SecurityException)
            {
                skipped.Add(new SkippedFile(file.NormalizedRelativePath, $"{ex.GetType().Name}: {ex.Message}"));
            }
        }

        return new FileScanResult(records, skipped);
    }

    // The per-file size cap from FUSE_MAX_FILE_BYTES, or the default; a non-positive override disables the cap.
    private static long ResolveMaxFileBytes() =>
        long.TryParse(Environment.GetEnvironmentVariable(MaxFileBytesEnvVar), out var bytes) ? bytes : DefaultMaxFileBytes;

    // Decode a UTF-8 prefix for the test/generated content heuristics, skipping a BOM if present.
    private static string DecodePrefix(byte[] bytes)
    {
        var start = 0;
        if (bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF)
            start = 3;

        var length = Math.Min(ContentPrefixBytes, bytes.Length - start);
        return length <= 0 ? string.Empty : Encoding.UTF8.GetString(bytes, start, length);
    }
}

/// <summary>
///     A request to scan a workspace for indexable files.
/// </summary>
/// <param name="RootDirectory">The workspace root to scan.</param>
/// <param name="Extensions">The file extensions to include; defaults to the .NET source and config set when null.</param>
public sealed record FileScanRequest(
    string RootDirectory,
    IReadOnlyCollection<string>? Extensions = null);

/// <summary>
///     The result of a workspace scan: the indexable file records, and the files skipped with the reason each was
///     skipped (R35), so one hostile file never aborts the index and the skips are visible in doctor.
/// </summary>
/// <param name="Files">The files that were read and turned into index records.</param>
/// <param name="Skipped">The files skipped (too large, unreadable, permission-denied) and why.</param>
public sealed record FileScanResult(
    IReadOnlyList<IndexedFileRecord> Files,
    IReadOnlyList<SkippedFile> Skipped);

/// <summary>A file the scanner skipped during indexing, with the reason (R35).</summary>
/// <param name="Path">The file's normalized relative path.</param>
/// <param name="Reason">A short human-readable reason (too large, IO error, access denied).</param>
public sealed record SkippedFile(string Path, string Reason);
