using DotMake.CommandLine;
using Fuse.Cli.Mcp;
using Fuse.Collection.Models;
using Fuse.Fusion;
using Fuse.Fusion.Scoping;
using Fuse.Plugins.Abstractions.Options;

namespace Fuse.Cli.Commands;

/// <summary>
///     Gives Fuse a natural-language task and a token budget and lets it pick the scoping strategy, the same
///     deterministic routing the <c>fuse_ask</c> MCP tool uses, exposed on the CLI so the benchmark harness and
///     CI can measure the routed agent surface without an MCP client.
/// </summary>
[CliCommand(Name = "ask", Description = "Give a task and token budget; Fuse picks skeleton, focus, or search and packs to budget.", Parent = typeof(FuseCliCommand))]
public sealed class AskCommand : CommandBase
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="AskCommand" /> class for CLI option binding only.
    /// </summary>
    /// <remarks>
    ///     Used by DotMake.CommandLine to bind options; the base services are <see langword="null" />, so this
    ///     instance must not run fusion.
    /// </remarks>
    public AskCommand() : base(null!, null!, null!, null!)
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="AskCommand" /> class.
    /// </summary>
    /// <param name="orchestrator">The fusion orchestrator.</param>
    /// <param name="templateRegistry">The project template registry.</param>
    /// <param name="consoleUI">The console UI for status output.</param>
    /// <param name="skeletonExtractors">Skeleton extractors resolved by file extension.</param>
    public AskCommand(
        FusionOrchestrator orchestrator,
        Fuse.Collection.Templates.ProjectTemplateRegistry templateRegistry,
        Fuse.Cli.Services.IConsoleUI consoleUI,
        Fuse.Plugins.Abstractions.CapabilityRegistry<Fuse.Plugins.Abstractions.Skeleton.ISkeletonExtractor> skeletonExtractors)
        : base(orchestrator, templateRegistry, skeletonExtractors, consoleUI)
    {
    }

    /// <summary>
    ///     The default token budget when <c>--max-tokens</c> is not supplied, matching the <c>fuse_ask</c> tool.
    /// </summary>
    private const int DefaultBudget = 20000;

    /// <summary>
    ///     Runs the <c>ask</c> command: derive a scoping plan from the task and budget, then fuse with that plan,
    ///     falling back from focus to search when the named type does not resolve.
    /// </summary>
    /// <param name="context">The CLI invocation context supplying the cancellation token.</param>
    /// <returns>A task that completes when fusion finishes and results have been written and reported.</returns>
    public Task RunAsync(CliContext context) => RunAsync(context.CancellationToken);

    /// <summary>
    ///     Runs the command with an explicit cancellation token. Separated from the <see cref="CliContext" />
    ///     entry point so the routing and fallback can be exercised in tests without the CLI framework.
    /// </summary>
    /// <param name="cancellationToken">Token used to cancel the fusion run.</param>
    /// <returns>A task that completes when fusion finishes and results have been written and reported.</returns>
    public async Task RunAsync(CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(Task))
        {
            WriteAskError("Error: --task must be a non-empty description of what you need.");
            return;
        }

        var budget = MaxTokens is > 0 ? MaxTokens.Value : DefaultBudget;
        MaxTokens = budget;

        var plan = AskStrategySelector.Select(Task, budget);

        var primary = BuildRequest(plan);
        // Focus can resolve nothing when the named type is not collected; fall back to a budgeted search so a
        // wrong guess degrades into a broader result rather than failing, matching the fuse_ask tool.
        var fallback = plan.Mode == AskMode.Focus
            ? BuildRequest(new AskPlan(AskMode.Search, null, plan.Depth))
            : null;

        await ExecuteFusionAsync(primary, cancellationToken, fallback);
    }

    private FusionRequest BuildRequest(AskPlan plan)
    {
        var builder = CreateRequestBuilder(ProjectTemplate.DotNet)
            .WithCollectionBehavior(
                Recursive,
                IgnoreBinary,
                ExcludeEmptyFiles,
                ExcludeAutoGenerated,
                ExcludeTestProjects,
                false,
                RespectGitIgnore)
            .WithReductionOptions(new ReductionOptions(
                level: plan.Mode == AskMode.Skeleton ? ReductionLevel.Skeleton : ReductionLevel.Aggressive,
                trimContent: true,
                useCondensing: true,
                enableRedaction: !NoRedact));

        if (plan.Mode == AskMode.Focus && plan.Seed is not null)
            builder.WithFocusOptions(new FocusOptions(plan.Seed, plan.Depth));
        else if (plan.Mode == AskMode.Search)
            builder.WithQueryOptions(new QueryOptions(Task!, 10, plan.Depth));

        return builder.Build();
    }

    private void WriteAskError(string message) => Console.Error.WriteLine(message);

    /// <summary>
    ///     The natural-language task describing what the caller needs to do or find.
    /// </summary>
    [CliOption(Required = true, Description = "What you need to do or find, in natural language.")]
    public string? Task { get; set; }
}
