using Fuse.Collection;
using Fuse.Collection.FileSystem;
using Fuse.Collection.Filters;
using Fuse.Collection.Templates;
using Fuse.Reduction;
using Fuse.Collection.Templates.Definitions;
using Fuse.Emission;
using Fuse.Emission.Tokenization;
using Fuse.Reduction.Reducers;
using Fuse.Reduction.Reducers.Implementations;
using Fuse.Reduction.Tokenization;
using Microsoft.Extensions.DependencyInjection;

namespace Fuse.Fusion.Extensions;

/// <summary>
///     Extension methods for registering Fuse fusion services with dependency injection.
/// </summary>
public static class ServiceCollectionExtensions
{
    /// <summary>
    ///     Registers all Fuse fusion services required to execute the collection, reduction, and emission pipelines.
    /// </summary>
    /// <param name="services">The service collection to configure.</param>
    /// <returns>The same service collection for chaining.</returns>
    public static IServiceCollection AddFuse(this IServiceCollection services)
    {
        services.AddSingleton<ITokenCounter>(_ => TikTokenCounter.Instance);
        services.AddSingleton<FusionValidator>();
        services.AddSingleton<FusionOrchestrator>();

        services.AddTransient<FileCollectionPipeline>();
        services.AddTransient<ContentReductionPipeline>();
        services.AddTransient<EmissionPipeline>();

        services.AddSingleton<IFileSystem, PhysicalFileSystem>();
        services.AddSingleton<GitIgnoreParser>();
        services.AddSingleton<ProjectTemplateRegistry>();
        services.AddSingleton<ReducerRegistry>();
        services.AddSingleton<OutputNamingService>();

        RegisterFileFilters(services);
        RegisterContentReducers(services);
        RegisterProjectTemplates(services);

        return services;
    }

    private static void RegisterFileFilters(IServiceCollection services)
    {
        services.AddTransient<IFileFilter, GitIgnoreFilter>();
        services.AddTransient<IFileFilter, ExtensionFilter>();
        services.AddTransient<IFileFilter, ExcludedDirectoryFilter>();
        services.AddTransient<IFileFilter, TestProjectFilter>();
        services.AddTransient<IFileFilter, UnitTestProjectFilter>();
        services.AddTransient<IFileFilter, FileSizeFilter>();
        services.AddTransient<IFileFilter, BinaryFileFilter>();
        services.AddTransient<IFileFilter, EmptyFileFilter>();
        services.AddTransient<IFileFilter, AutoGeneratedFileFilter>();
        services.AddTransient<IFileFilter, ExcludedFileNameFilter>();
        services.AddTransient<IFileFilter, GlobPatternFilter>();
    }

    private static void RegisterContentReducers(IServiceCollection services)
    {
        services.AddSingleton<IContentReducer, CSharpReducer>();
        services.AddSingleton<IContentReducer, CssReducer>();
        services.AddSingleton<IContentReducer, HtmlReducer>();
        services.AddSingleton<IContentReducer, JavaScriptReducer>();
        services.AddSingleton<IContentReducer, JsonReducer>();
        services.AddSingleton<IContentReducer, MarkdownReducer>();
        services.AddSingleton<IContentReducer, RazorReducer>();
        services.AddSingleton<IContentReducer, ScssReducer>();
        services.AddSingleton<IContentReducer, XmlReducer>();
        services.AddSingleton<IContentReducer, YamlReducer>();
    }

    private static void RegisterProjectTemplates(IServiceCollection services)
    {
        services.AddSingleton<IProjectTemplate, AzureDevOpsWikiTemplate>();
        services.AddSingleton<IProjectTemplate, ClojureTemplate>();
        services.AddSingleton<IProjectTemplate, CppCSharpTemplate>();
        services.AddSingleton<IProjectTemplate, DartTemplate>();
        services.AddSingleton<IProjectTemplate, DotNetTemplate>();
        services.AddSingleton<IProjectTemplate, ElixirTemplate>();
        services.AddSingleton<IProjectTemplate, ErlangTemplate>();
        services.AddSingleton<IProjectTemplate, FsharpTemplate>();
        services.AddSingleton<IProjectTemplate, GenericTemplate>();
        services.AddSingleton<IProjectTemplate, GoTemplate>();
        services.AddSingleton<IProjectTemplate, HaskellTemplate>();
        services.AddSingleton<IProjectTemplate, InfrastructureTemplate>();
        services.AddSingleton<IProjectTemplate, JavaScriptTemplate>();
        services.AddSingleton<IProjectTemplate, JavaTemplate>();
        services.AddSingleton<IProjectTemplate, KotlinTemplate>();
        services.AddSingleton<IProjectTemplate, LuaTemplate>();
        services.AddSingleton<IProjectTemplate, PerlTemplate>();
        services.AddSingleton<IProjectTemplate, PhpTemplate>();
        services.AddSingleton<IProjectTemplate, PythonTemplate>();
        services.AddSingleton<IProjectTemplate, RTemplate>();
        services.AddSingleton<IProjectTemplate, RubyTemplate>();
        services.AddSingleton<IProjectTemplate, RustTemplate>();
        services.AddSingleton<IProjectTemplate, ScalaTemplate>();
        services.AddSingleton<IProjectTemplate, SwiftTemplate>();
        services.AddSingleton<IProjectTemplate, TypeScriptTemplate>();
        services.AddSingleton<IProjectTemplate, VbNetTemplate>();
    }
}
