using Fuse.Collection.Models;

namespace Fuse.Collection.Options;

/// <summary>
///     Configuration options for the file collection pipeline.
/// </summary>
/// <remarks>
///     Extension and exclusion lists are resolved before collection begins.
///     CLI inputs such as include, exclude, and only-extensions are merged into
///     <see cref="Extensions" /> and related properties by <c>FusionRequestBuilder</c>.
/// </remarks>
public sealed record CollectionOptions
{
    /// <summary>
    ///     Gets the root directory to scan for source files.
    /// </summary>
    public string SourceDirectory { get; init; }

    /// <summary>
    ///     Gets the project template used to resolve default extensions and exclusions.
    /// </summary>
    public ProjectTemplate? Template { get; init; }

    /// <summary>
    ///     Gets the resolved file extensions to include in the collection.
    /// </summary>
    public IReadOnlyCollection<string> Extensions { get; init; }

    /// <summary>
    ///     Gets directory names to exclude from scanning.
    /// </summary>
    public IReadOnlyCollection<string> ExcludeDirectories { get; init; }

    /// <summary>
    ///     Gets specific file names to exclude from the collection.
    /// </summary>
    public IReadOnlyCollection<string> ExcludeFiles { get; init; }

    /// <summary>
    ///     Gets glob patterns that exclude matching files from the collection.
    /// </summary>
    public IReadOnlyCollection<string> ExcludePatterns { get; init; }

    /// <summary>
    ///     Gets the maximum file size in kilobytes. Zero means no limit.
    /// </summary>
    public int MaxFileSizeKb { get; init; }

    /// <summary>
    ///     Gets a value indicating whether subdirectories are scanned recursively.
    /// </summary>
    public bool Recursive { get; init; }

    /// <summary>
    ///     Gets a value indicating whether binary files are skipped.
    /// </summary>
    public bool IgnoreBinaryFiles { get; init; }

    /// <summary>
    ///     Gets a value indicating whether zero-byte files are skipped.
    /// </summary>
    public bool ExcludeEmptyFiles { get; init; }

    /// <summary>
    ///     Gets a value indicating whether auto-generated files are skipped.
    /// </summary>
    public bool ExcludeAutoGenerated { get; init; }

    /// <summary>
    ///     Gets a value indicating whether all test project directories are excluded.
    /// </summary>
    public bool ExcludeTestProjects { get; init; }

    /// <summary>
    ///     Gets a value indicating whether unit test project directories are excluded.
    /// </summary>
    public bool ExcludeUnitTestProjects { get; init; }

    /// <summary>
    ///     Gets a value indicating whether <c>.gitignore</c> rules are honored.
    /// </summary>
    public bool RespectGitIgnore { get; init; }

    /// <summary>
    ///     Initializes a new instance of the <see cref="CollectionOptions" /> record.
    /// </summary>
    /// <param name="sourceDirectory">The root directory to scan.</param>
    /// <param name="template">The project template for default extensions and exclusions.</param>
    /// <param name="extensions">The resolved extension list.</param>
    /// <param name="excludeDirectories">Directory names to exclude.</param>
    /// <param name="excludeFiles">Specific file names to exclude.</param>
    /// <param name="excludePatterns">Glob patterns to exclude.</param>
    /// <param name="maxFileSizeKb">Maximum file size in kilobytes; zero means unlimited.</param>
    /// <param name="recursive">Whether to scan subdirectories.</param>
    /// <param name="ignoreBinaryFiles">Whether to skip binary files.</param>
    /// <param name="excludeEmptyFiles">Whether to skip zero-byte files.</param>
    /// <param name="excludeAutoGenerated">Whether to skip auto-generated files.</param>
    /// <param name="excludeTestProjects">Whether to exclude all test project directories.</param>
    /// <param name="excludeUnitTestProjects">Whether to exclude unit test project directories.</param>
    /// <param name="respectGitIgnore">Whether to honor <c>.gitignore</c> rules.</param>
    public CollectionOptions(
        string sourceDirectory,
        ProjectTemplate? template = null,
        IReadOnlyCollection<string>? extensions = null,
        IReadOnlyCollection<string>? excludeDirectories = null,
        IReadOnlyCollection<string>? excludeFiles = null,
        IReadOnlyCollection<string>? excludePatterns = null,
        int maxFileSizeKb = 0,
        bool recursive = true,
        bool ignoreBinaryFiles = true,
        bool excludeEmptyFiles = true,
        bool excludeAutoGenerated = true,
        bool excludeTestProjects = false,
        bool excludeUnitTestProjects = false,
        bool respectGitIgnore = true)
    {
        SourceDirectory = sourceDirectory;
        Template = template;
        Extensions = extensions ?? [];
        ExcludeDirectories = excludeDirectories ?? [];
        ExcludeFiles = excludeFiles ?? [];
        ExcludePatterns = excludePatterns ?? [];
        MaxFileSizeKb = maxFileSizeKb;
        Recursive = recursive;
        IgnoreBinaryFiles = ignoreBinaryFiles;
        ExcludeEmptyFiles = excludeEmptyFiles;
        ExcludeAutoGenerated = excludeAutoGenerated;
        ExcludeTestProjects = excludeTestProjects;
        ExcludeUnitTestProjects = excludeUnitTestProjects;
        RespectGitIgnore = respectGitIgnore;
    }
}
